version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    depends_on:
      - mongo

  html_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app.html:/usr/share/nginx/html/app.html

  mongo:
    image: mongo:latest  # Use the official MongoDB image
    ports:
      - "27017:27017"
